version: "2.0"

services: 
    server:
        image: nginx
        ports:
            - "8080:80"
        links:
            - app:app
            - contentful_builder:contentful_builder
        env_file: 
            - .env
        depends_on: 
            - app
            - contentful_builder
        volumes:
            - ./dist:/var/www:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    node_modules:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - /usr/src

    contentful_builder:
        image: node:7.7-alpine
        env_file: 
            - .env
        environment: 
            - INPUT_DIR=/usr/src/in
            - OUTPUT_DIR=/usr/src/out
        volumes:
            - ./builder:/usr/src/builder
            - ./dist:/usr/src/out
            - ./src:/usr/src/in
        volumes_from:
            - node_modules
        depends_on: 
            - node_modules
        working_dir: /usr/src
        entrypoint: npm run server:dev

    app:
        image: node:7.7-alpine
        env_file: 
            - .env
        volumes:
            - ./app:/usr/src/app
        volumes_from:
            - node_modules
        depends_on: 
            - node_modules
        working_dir: /usr/src
        entrypoint: npm run app:dev