version: "2.0"

services: 

    # the proxy server. This serves the routes to the webhook and app.
    # ...however its primary goal is to serve the static files
    server:
        image: nginx
        ports:
            - "8080:80"
        links:
            - app:app
        env_file: 
            - .env
        depends_on: 
            - app
        volumes:
            - ./dist:/var/www:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

    # the app server is mounted to /app on the proxy server and contains logic for payments (and gps?)
    app:
        build:
            dockerfile: Dockerfile.dev
            context: .
        env_file: 
            - .env
        environment: 
            - SRC_DIR=/usr/src/app/src
            - DIST_DIR=/usr/src/app/dist
            - NODE_ENV=development
        volumes:
            - .:/usr/src/app
            - node_modules_data:/usr/src/app/node_modules
        working_dir: /usr/src/app
        entrypoint: npm 
        command: run dev

volumes: 
    node_modules_data: