version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:8

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: ls node_modules/.bin
      
      - run: npm -v && node -v

      - run: ./node_modules/.bin/now --token=$NOW_TOKEN deploy --team devoorhoede

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
